spring:
  application:
    name: account
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Yuri123.
    url: jdbc:postgresql://116.196.122.231:5432/graphql
    hikari:
      schema: user

graphql:
  packages:
    - "org.study.account.graphql"
    - "org.study.account.model"
    - "org.study.account.exception"
